export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_START = 'AUTH_START';
export const AUTH_REGISTER = "AUTH_REGISTER";
export const CHANGE_ACTIVE_SHOPPING_CART = "CHANGE_ACTIVE_SHOPPING_CART";

export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'
export const GET_MENU_ERROR = 'GET_MENU_ERROR'

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';
export const ADD_ITEM_IN_CATEGORY = 'ADD_ITEM_IN_CATEGORY';
export const EDIT_ITEM_IN_CATEGORY = 'EDIT_ITEM_IN_CATEGORY';
export const DELETE_ITEM_IN_CATEGORY = 'DELETE_ITEM_IN_CATEGORY';

export const SET_CURRENT_ITEM_PRICE = "SET_CURRENT_ITEM_PRICE";
export const ADD_ITEM_PRICE_IN_ITEM = 'ADD_ITEM_PRICE_IN_ITEM';
export const DELETE_ITEM_PRICE_IN_ITEM = 'DELETE_ITEM_PRICE_IN_ITEM';

export const GET_SHOPPING_CART_HISTORY = 'GET_SHOPPING_CART_HISTORY';
export const GET_SHOPPING_CART_HISTORY_ERROR = 'GET_SHOPPING_CART_HISTORY_ERROR';
export const GET_SHOPPING_CART_HISTORY_DETAILS = "GET_SHOPPING_CART_HISTORY_DETAILS";
export const GET_SHOPPING_CART_HISTORY_DETAILS_ERROR = "GET_SHOPPING_CART_HISTORY_DETAILS_ERROR";
export const ADD_ITEM_IN_CART = "ADD_ITEM_IN_CART";
export const ADD_ITEM_IN_CART_ERROR = "ADD_ITEM_IN_CART_ERROR";
export const GET_SHOPPING_CART = "GET_SHOPPING_CART";
export const GET_SHOPPING_CART_ERROR = "GET_SHOPPING_CART_ERROR";
export const PAY_SHOPPING_CART = "PAY_SHOPPING_CART";
export const PAY_SHOPPING_CART_ERROR = "PAY_SHOPPING_CART_ERROR";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const DELETE_ITEM_FROM_CART_ERROR = "DELETE_ITEM_FROM_CART_ERROR";
export const CHANGE_ITEM_QUANTITY_ERROR = "CHANGE_ITEM_QUANTITY_ERROR";
export const INCREASE = "INCREASE";
export const DECREASE = "DECREASE";
export const SET_CURRENT_CART_DETAILS = "SET_CURRENT_CART_DETAILS";

export const GET_ADDRESSES_FOR_USER = "GET_ADDRESSES_FOR_USER";
export const ADD_NEW_ADDRESS_FOR_USER = "ADD_NEW_ADDRESS_FOR_USER";
export const DELETE_ADDRESS_FOR_USER = "DELETE_ADDRESS_FOR_USER";
export const SET_SELECTED_ADDRESS = "SET_SELECTED_ADDRESS";
export const EDIT_ADDRESS_FOR_USER = "EDIT_ADDRESS_FOR_USER";
export const UPDATE_COORDINATES = "UPDATE_COORDINATES";
