export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_START = 'AUTH_START';
export const AUTH_REGISTER = "AUTH_REGISTER";

export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS'
export const GET_MENU_ERROR = 'GET_MENU_ERROR'

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';
export const ADD_ITEM_IN_CATEGORY = 'ADD_ITEM_IN_CATEGORY';
export const EDIT_ITEM_IN_CATEGORY = 'EDIT_ITEM_IN_CATEGORY';
export const DELETE_ITEM_IN_CATEGORY = 'DELETE_ITEM_IN_CATEGORY';

export const ADD_ITEM_PRICE_IN_ITEM = 'ADD_ITEM_PRICE_IN_ITEM';
export const DELETE_ITEM_PRICE_IN_ITEM = 'DELETE_ITEM_PRICE_IN_ITEM';

export const GET_SHOPPING_CART_HISTORY = 'GET_SHOPPING_CART_HISTORY';
export const GET_SHOPPING_CART_HISTORY_ERROR = 'GET_SHOPPING_CART_HISTORY_ERROR';
export const ADD_ITEM_IN_CART = "ADD_ITEM_IN_CART";
export const ADD_ITEM_IN_CART_ERROR = "ADD_ITEM_IN_CART_ERROR";
export const GET_SHOPPING_CART = "GET_SHOPPING_CART";
export const GET_SHOPPING_CART_ERROR = "GET_SHOPPING_CART_ERROR";
export const PAY_SHOPPING_CART = "PAY_SHOPPING_CART";
export const PAY_SHOPPING_CART_ERROR = "PAY_SHOPPING_CART_ERROR";
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const DELETE_ITEM_FROM_CART_ERROR = "DELETE_ITEM_FROM_CART_ERROR";
export const CHANGE_ITEM_QUANTITY = "CHANGE_ITEM_QUANTITY";
export const CHANGE_ITEM_QUANTITY_ERROR = "CHANGE_ITEM_QUANTITY_ERROR";
